from pathlib import Path
import sqlglot
ROOT=Path(__file__).resolve().parents[1]
OBJECTS=[('10_diesel.sql','DT_DIESEL_WEEKLY'),('20_clocks.sql','DT_SURCHARGE_CLOCKS'),('30_spread.sql','DT_MARGIN_SPREAD'),('40_summary.sql','DT_SCENARIO_SUMMARY')]
def render():
 out=['-- UNVERIFIED: confirm in Snowflake. Generated by local/render_snowflake.py.','USE ROLE FUEL_ANALYST; USE DATABASE FUEL_TIMING; USE WAREHOUSE FUEL_WH;','ALTER SESSION SET WEEK_START = 1;']
 for file,name in OBJECTS:
  select=sqlglot.transpile((ROOT/'sql/selects'/file).read_text(),read='duckdb',write='snowflake',pretty=True)[0]
  lag="'1 day'" if name=='DT_SCENARIO_SUMMARY' else 'DOWNSTREAM'
  out.append(f'CREATE OR REPLACE DYNAMIC TABLE MODEL.{name}\nTARGET_LAG = {lag} WAREHOUSE = FUEL_WH REFRESH_MODE = FULL INITIALIZE = ON_CREATE AS\n{select};')
 out.extend(['CREATE OR REPLACE VIEW MODEL.V_PARAMETERS AS SELECT * FROM CONFIG.PARAMETERS;', 'CREATE OR REPLACE VIEW MODEL.V_LOAD_LOG AS SELECT * FROM RAW.LOAD_LOG;', 'CREATE OR REPLACE VIEW MODEL.V_QUARANTINE AS SELECT * FROM RAW.QUARANTINE;'])
 (ROOT/'sql/04_dynamic_tables.sql').write_text('\n\n'.join(out)+'\n')
if __name__=='__main__':render()
