-- UNVERIFIED: confirm in Snowflake. Administrative bootstrap only.
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS FUEL_ANALYST;
GRANT ROLE FUEL_ANALYST TO ROLE SYSADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS FUEL_RM WITH CREDIT_QUOTA = 5
 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
 TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO SUSPEND ON 100 PERCENT DO SUSPEND_IMMEDIATE;
CREATE WAREHOUSE IF NOT EXISTS FUEL_WH WAREHOUSE_SIZE = XSMALL
 AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
ALTER WAREHOUSE FUEL_WH SET RESOURCE_MONITOR = FUEL_RM;
CREATE DATABASE IF NOT EXISTS FUEL_TIMING;
GRANT OWNERSHIP ON DATABASE FUEL_TIMING TO ROLE FUEL_ANALYST COPY CURRENT GRANTS;
GRANT USAGE, OPERATE ON WAREHOUSE FUEL_WH TO ROLE FUEL_ANALYST;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE FUEL_ANALYST;
USE ROLE FUEL_ANALYST;
USE DATABASE FUEL_TIMING;
USE WAREHOUSE FUEL_WH;
ALTER SESSION SET WEEK_START = 1;
CREATE SCHEMA IF NOT EXISTS CONFIG;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS MODEL;
CREATE SCHEMA IF NOT EXISTS APP;
-- Source grants must be configured by the account administrator after profiling.
-- The functional role owns project schemas and model objects; account resources
-- remain administratively owned to avoid granting account-level CREATE privileges.
