-- UNVERIFIED: confirm in Snowflake. Generated by local/render_snowflake.py.

USE ROLE FUEL_ANALYST; USE DATABASE FUEL_TIMING; USE WAREHOUSE FUEL_WH;

ALTER SESSION SET WEEK_START = 1;

CREATE OR REPLACE DYNAMIC TABLE MODEL.DT_DIESEL_WEEKLY
TARGET_LAG = DOWNSTREAM WAREHOUSE = FUEL_WH REFRESH_MODE = FULL INITIALIZE = ON_CREATE AS
/* SYNTHETIC locally; identical SELECT translated to Snowflake deployment syntax. */
WITH w AS (
  SELECT
    r.*,
    p.regime_threshold,
    p.as_of_date,
    prior.price AS prior_4week_price,
    AVG(r.price) OVER (
      PARTITION BY r.geo_id
      ORDER BY r.week_date
      ROWS BETWEEN 25 PRECEDING AND 26 FOLLOWING
    ) AS centered_avg,
    COUNT(*) OVER (
      PARTITION BY r.geo_id
      ORDER BY r.week_date
      ROWS BETWEEN 25 PRECEDING AND 26 FOLLOWING
    ) AS window_count,
    MIN(r.week_date) OVER (
      PARTITION BY r.geo_id
      ORDER BY r.week_date
      ROWS BETWEEN 25 PRECEDING AND 26 FOLLOWING
    ) AS window_start,
    MAX(r.week_date) OVER (
      PARTITION BY r.geo_id
      ORDER BY r.week_date
      ROWS BETWEEN 25 PRECEDING AND 26 FOLLOWING
    ) AS window_end
  FROM raw.diesel_weekly AS r
  CROSS JOIN config.parameters AS p
  LEFT JOIN raw.diesel_weekly AS prior
    ON r.geo_id = prior.geo_id AND prior.week_date = r.week_date - INTERVAL '28 DAYS'
)
SELECT
  *,
  price / NULLIF(NULLIF(prior_4week_price, 0), 0) - 1 AS change_4week,
  CASE
    WHEN prior_4week_price IS NULL
    THEN 'UNCLASSIFIED'
    WHEN price / NULLIF(prior_4week_price, 0) - 1 >= regime_threshold
    THEN 'RISING'
    WHEN price / NULLIF(prior_4week_price, 0) - 1 <= -regime_threshold
    THEN 'FALLING'
    ELSE 'PLATEAU'
  END AS regime,
  DATE_PART(MONTH, week_date) AS month_number,
  CASE
    WHEN DATE_PART(MONTH, week_date) IN (10, 11, 12, 1, 2, 3)
    THEN 'HEATING'
    ELSE 'NON_HEATING'
  END AS season,
  CASE
    WHEN window_count = 52 AND DATEDIFF(DAY, window_start, window_end) = 357
    THEN price / NULLIF(centered_avg, 0)
  END AS seasonal_ratio
FROM w;

CREATE OR REPLACE DYNAMIC TABLE MODEL.DT_SURCHARGE_CLOCKS
TARGET_LAG = DOWNSTREAM WAREHOUSE = FUEL_WH REFRESH_MODE = FULL INITIALIZE = ON_CREATE AS
WITH eligible AS (
  SELECT
    d.*,
    i.price AS index_price,
    p.base_price,
    p.mpg,
    p.step_up_per_mile,
    p.load_miles,
    p.index_lag_weeks,
    s.*,
    CASE s.reset_frequency
      WHEN 'WEEKLY'
      THEN d.week_date
      WHEN 'MONTHLY'
      THEN DATE_TRUNC('MONTH', d.week_date)
      ELSE DATE_TRUNC('QUARTER', d.week_date)
    END AS reset_period
  FROM model.dt_diesel_weekly AS d
  CROSS JOIN config.parameters AS p
  CROSS JOIN config.contract_scenarios AS s
  JOIN raw.diesel_weekly AS i
    ON d.geo_id = i.geo_id
    AND i.week_date = d.week_date - p.index_lag_weeks * INTERVAL '7 DAYS'
), reset AS (
  SELECT
    *,
    FIRST_VALUE(index_price) OVER (
      PARTITION BY geo_id, scenario_id, reset_period
      ORDER BY week_date
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS reset_price,
    MIN(week_date) OVER (PARTITION BY geo_id, scenario_id, reset_period) AS reset_week
  FROM eligible
)
SELECT
  *,
  GREATEST(0.0, (
    index_price - base_price
  ) / NULLIF(mpg, 0)) AS carrier_fsc,
  GREATEST(0.0, (
    reset_price - base_price
  ) / NULLIF(mpg, 0)) + CASE WHEN seasonal_clause AND season = 'HEATING' THEN step_up_per_mile ELSE 0 END AS shipper_fsc,
  CASE reset_frequency
    WHEN 'WEEKLY'
    THEN TRUE
    WHEN 'MONTHLY'
    THEN DATE_TRUNC('MONTH', week_date) < DATE_TRUNC('MONTH', as_of_date)
    ELSE DATE_TRUNC('QUARTER', week_date) < DATE_TRUNC('QUARTER', as_of_date)
  END AS complete_period
FROM reset;

CREATE OR REPLACE DYNAMIC TABLE MODEL.DT_MARGIN_SPREAD
TARGET_LAG = DOWNSTREAM WAREHOUSE = FUEL_WH REFRESH_MODE = FULL INITIALIZE = ON_CREATE AS
SELECT
  *,
  shipper_fsc - carrier_fsc AS spread,
  (
    shipper_fsc - carrier_fsc
  ) * load_miles * 1000 AS dollars_per_1000_loads
FROM model.dt_surcharge_clocks;

CREATE OR REPLACE DYNAMIC TABLE MODEL.DT_SCENARIO_SUMMARY
TARGET_LAG = '1 day' WAREHOUSE = FUEL_WH REFRESH_MODE = FULL INITIALIZE = ON_CREATE AS
SELECT
  geo_id,
  scenario_id,
  reset_frequency,
  seasonal_clause,
  COUNT(*) AS weeks,
  SUM(spread) AS sum_spread,
  AVG(spread) AS mean_spread,
  AVG(dollars_per_1000_loads) AS mean_dollars_per_1000_loads,
  AVG(CASE WHEN spread < 0 THEN 1.0 ELSE 0.0 END) AS squeeze_share,
  PERCENTILE_CONT(0.10) WITHIN GROUP (ORDER BY
    spread) AS p10,
  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY
    spread) AS p50,
  PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY
    spread) AS p90,
  MIN(week_date) AS start_date,
  MAX(week_date) AS end_date
FROM model.dt_margin_spread
WHERE
  complete_period
GROUP BY
  geo_id,
  scenario_id,
  reset_frequency,
  seasonal_clause;

CREATE OR REPLACE VIEW MODEL.V_PARAMETERS AS SELECT * FROM CONFIG.PARAMETERS;

CREATE OR REPLACE VIEW MODEL.V_LOAD_LOG AS SELECT * FROM RAW.LOAD_LOG;

CREATE OR REPLACE VIEW MODEL.V_QUARANTINE AS SELECT * FROM RAW.QUARANTINE;
