-- UNVERIFIED: confirm in Snowflake. Destructive: dedicated project objects only.
-- Run only when intentionally tearing down FUEL_TIMING. Never include in build run order.
USE ROLE ACCOUNTADMIN;
ALTER TASK IF EXISTS FUEL_TIMING.RAW.TASK_LOAD_DIESEL_WEEKLY SUSPEND;
DROP TASK IF EXISTS FUEL_TIMING.RAW.TASK_LOAD_DIESEL_WEEKLY;
DROP DATABASE IF EXISTS FUEL_TIMING;
DROP WAREHOUSE IF EXISTS FUEL_WH;
DROP RESOURCE MONITOR IF EXISTS FUEL_RM;
DROP ROLE IF EXISTS FUEL_ANALYST;
